### PR TITLE
client action example is wrong, name is a url

### PR DESCRIPTION
**Pull request by troyibm**
See this developerWorks article: https://developer.ibm.com/answers/questions/479521/web-service-i.html?childToView=479597#answer-479597

### CODE REVIEW

**Comment by michelle-miller** [comment]
The name parameter calls your custom code, whatever that might be. it might be a web service (apparently, though i'm surprised this works), but the key point is that it is your own custom app. so, i don't want to change the example to show a url. i want it to be clear that it will call your custom code. and the assumption is that you have some client app running in the environment that will execute when called from the dialog.
it's not clear to me which part of the dw Answers conversation you want me to look at. the exchange seems to confirm what is currently documented, but i might be missing something.

**Comment by nguyen-j** [comment]
Sorry Michelle, Troy opened up this issue on my behalf. As I was trying to find out if it's possible to call an external service from WA dialog, I came across this article misunderstood it. I thought it was possible to have WA dialog directly make a call to a url, but after rereading I understand now that a wrapper needs to be written for the external service, or the client application must handle it.

**Comment by troyibm** [comment]
Still feels like there is something missing though.  If Jason didn't understand it, then I'm sure others won't as well.  Maybe being specific that the name is a cloud function that then can do whatever you want??  How is the client action different from cloud_function if they both call a cloud function?  I admit that I haven't read this thoroughly, but something was confusing and feel that something should be added that would make this clearer.

**Comment by troyibm** [comment]
Also, isn't the variable name wrong in the last sentence of the paragraph (line 276)?  The JSON for client action uses 'my_forecast' not 'forecast'.  If you want me to add another commit that removes the URL but keeps the change to the variable name, I can.

**Comment by michelle-miller** [comment]
yeah, it is confusing. after others asked similar questions, i changed the description to state this. 
"When you define the programmatic call, you choose one of the following types:

- client: Defines a programmatic call in a standardized format that your external client application can understand. Your client application must use the provided information to run the programmatic call or function, and return the result to the dialog. This type of call basically tells the dialog to pause here and wait for the client application go do something. The program that the client application runs can be anything that you choose. Be sure to specify the call name and parameter details, and the error message variable name, according to the JSON formatting rules that are outlined later.

- cloud_function: Calls an Cloud Functions action directly, and returns the result to the dialog. You must provide a Cloud Functions authentication key with the call. (This type used to be named server. The type server continues to be supported.)

- web_action: Calls a Cloud Functions web action. Web actions are annotated Cloud Functions actions that developers can use to program backend logic that a web application can access anonymously, without requiring a Cloud Functions authentication key. Although authentication isn't required, web actions can be secured in the following ways:

      - With an authentication token that is specific to the web action, and can be revoked or changed by the action owner at any time
      - By passing your Cloud Functions credentials"
i can't think of a better way to explain it.

**Comment by troyibm** [comment]
I'll close this pull request and open another after we go over what we have done with the client type of action.  I'll think more about what could be said that would save others some time.

**Pull request closed without merging**
